// Generated by scripts/generate-contracts.py; do not edit.
export interface PhotoCircuitComponent {
  ref: string;
  kind: string;
  nodes: Array<string | null>;
  value_si: number | null;
  source: "image_visible" | "user_reported" | "assumed" | "unknown";
  value_source: "image_visible" | "user_reported" | "assumed" | "unknown";
  connection_source: "image_visible" | "user_reported" | "assumed" | "unknown";
}

export interface PhotoCircuitQuestion {
  target: string;
  issue: string;
  request: string;
}

export interface PhotoCircuitDraft {
  context_id: string;
  image_revision: string;
  draft_revision: string;
  graph_sha256: string | null;
  intended_function: string | null;
  components: Array<PhotoCircuitComponent>;
  ground_node: string | null;
  ground_source: "image_visible" | "user_reported" | "assumed" | "unknown";
  assumptions: Array<string>;
  uncertainties: Array<string>;
  unsupported: Array<string>;
  questions: Array<PhotoCircuitQuestion>;
  simulation_ready: boolean;
  retained_refs: Array<string>;
  prior_image_revision?: string;
}

export interface PhotoCircuitSimulation {
  status: "blocked" | "succeeded" | "failed" | "cancelled" | "timed_out";
  draft_revision: string;
  graph_sha256: string | null;
  provenance: "ngspice_actual" | "none";
  node_voltages_v: Record<string, number>;
  reason: string | null;
  conditional: true;
  simulation_id?: string;
  simulator_sha256?: string | null;
}

export interface PhotoCircuitModel {
  draft: PhotoCircuitDraft;
  simulation: PhotoCircuitSimulation | null;
}

export interface Revisions {
  circuit_revision: string | null;
  firmware_revision: string | null;
  calibration_revision: string | null;
}

export interface EventEnvelope {
  schema_version: "1.0.0";
  session_id: string;
  event_id: string;
  event_type: string;
  source: string;
  sequence: number;
  occurred_at: string;
  received_at: string;
  correlation_id: string;
  circuit_revision: string | null;
  firmware_revision: string | null;
  calibration_revision: string | null;
  payload: Record<string, unknown>;
  supersedes_event_id: string | null;
}

export interface MeasurementRequest {
  request_id: string;
  quantity: "voltage" | "resistance" | "continuity";
  meter_mode: "DC_voltage" | "AC_voltage" | "resistance" | "continuity";
  meter_range: string;
  black_node_id: string;
  red_node_id: string;
  target_ids: Array<string>;
  power_state: "off_verified" | "on_current_limited" | "unknown";
  instrument_id: string;
  permitted_units: Array<"V" | "ohm">;
  revisions: Revisions;
  measurement_context_hash: string;
  expires_at: string;
  status: "active" | "cancelled" | "completed" | "expired";
}

export interface MeasurementCandidate {
  candidate_id: string;
  request_id: string;
  original_text: string;
  value: string | null;
  si_unit: "V" | "ohm" | "A" | null;
  original_unit: string | null;
  original_number: string | null;
  display_state: "numeric" | "over_limit" | "unstable" | "unknown";
  source: "voice" | "ocr" | "typed" | "instrument";
  ambiguities: Array<string>;
}

export interface Confirmation {
  confirmation_id: string;
  candidate_id: string;
  request_id: string;
  measurement_context_hash: string;
  revisions: Revisions;
  readback_text: string;
  readback_completed: boolean;
  expires_at: string;
}
