"""Generate strict Python and TypeScript bindings from our small JSON Schema subset.

JSON Schema remains authoritative; schema validation covers bounds/formats in addition
to generated structural types. Run with --check in CI to catch stale generated files.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = json.loads((ROOT / "packages/contracts/schema.json").read_text())


def render_type(spec, language):
    if "anyOf" in spec:
        return " | ".join(render_type(item, language) for item in spec["anyOf"])
    if "$ref" in spec:
        return spec["$ref"].rsplit("/", 1)[-1]
    if "const" in spec or "enum" in spec:
        values = spec.get("enum", [spec.get("const")])
        if language == "py":
            return "Literal[" + ", ".join(repr(v) for v in values) + "]"
        return " | ".join(json.dumps(v) for v in values)
    kind = spec.get("type", "object")
    if isinstance(kind, list):
        return " | ".join(render_type({**spec, "type": k}, language) for k in kind)
    if kind == "array":
        inner = render_type(spec["items"], language)
        return f"list[{inner}]" if language == "py" else f"Array<{inner}>"
    if kind == "object" and isinstance(spec.get("additionalProperties"), dict):
        inner = render_type(spec["additionalProperties"], language)
        return f"dict[str, {inner}]" if language == "py" else f"Record<string, {inner}>"
    names = {"string": ("str", "string"), "number": ("float", "number"),
             "integer": ("int", "number"), "boolean": ("bool", "boolean"),
             "null": ("None", "null"), "object": ("dict[str, Any]", "Record<string, unknown>")}
    return names[kind][0 if language == "py" else 1]


def generate():
    py = ['# Generated by scripts/generate-contracts.py; do not edit.',
          'from typing import Any, Literal', 'from pydantic import BaseModel, ConfigDict', '',
          'class Contract(BaseModel):', '    model_config = ConfigDict(extra="forbid", strict=True)', '']
    ts = ['// Generated by scripts/generate-contracts.py; do not edit.']
    for name, schema in SCHEMA["$defs"].items():
        py += [f'class {name}(Contract):']
        ts += [f'export interface {name} {{']
        for field, spec in schema["properties"].items():
            required = field in schema.get("required", [])
            py += [f'    {field}: {render_type(spec, "py")}' + ('' if required else ' | None = None')]
            ts += [f'  {field}{"" if required else "?"}: {render_type(spec, "ts")};']
        py += ['', '']
        ts += ['}', '']
    return {
        ROOT / 'services/bench/src/ohmpath/contracts.py': '\n'.join(py).rstrip() + '\n',
        ROOT / 'packages/contracts/index.ts': '\n'.join(ts).rstrip() + '\n',
        ROOT / 'services/bench/src/ohmpath/contract-schema.json': json.dumps(SCHEMA, indent=2) + '\n',
    }


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Stale binding: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
